server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: pass-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/passes
#    username: root
#    password: root
#    driverClassName: org.postgresql.Driver
#  jpa:
#    database: POSTGRESQL
#    hibernate:
#      ddl-auto: create
#    show-sql: true
    datasource:
    url: jdbc:h2:mem:library
#    url: jdbc:h2:file:/data/library
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true